environment:
  name: ''

teams: {}

projects:
  user:
    includeNamespaces:
      - demo
    sourceRepos:
      - http://daocloud.github.io/dao-2048/
    clusterResourceWhitelist: []

applications: {}

namespaces:
  demo:
    annotations: {}
    labels: {}

certificateClusterIssuer: {}

argocd:
  namespace: argocd

gitops:
  repository: ''
  revisionHistoryLimit: 3
