applications:
  - name: kyverno
    owner: platform
    project: platform
    namespace: kyverno
    repo: https://kyverno.github.io/kyverno
    chart: kyverno
    version: "*"
    valueFiles: []
    autoSync:
      enabled: true
      syncOptions:
        - ServerSideApply=true
projects:
  platform:
    owner: platform
    clusterResourceWhitelist:
      - group: rbac.authorization.k8s.io
        kind: ClusterRoleBinding
      - group: rbac.authorization.k8s.io
        kind: ClusterRole
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
      - group: admissionregistration.k8s.io
        kind: MutatingWebhookConfiguration
      - group: apiregistration.k8s.io
        kind: APIService
      - group: scheduling.k8s.io
        kind: PriorityClass

namespaces:
  argocd:
    owner: platform
    project: platform
  kyverno:
    owner: platform
    project: platform
---
environment:
  name: demo-cluster

teams:
  platform:
    clusterAdmin: true

argocd:
  namespace: argocd

gitops:
  repository: https://github.com/qasmi/smart-idp.git
  revision: demo-luc
  revisionHistoryLimit: 3
